// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FKbB335o1rEe_kQHTLH_R04fvIUt5Do',
    appId: '1:531941429147:web:fedc2086cbca53bf611b3e',
    messagingSenderId: '531941429147',
    projectId: 'bookstash-14e34',
    authDomain: 'bookstash-14e34.firebaseapp.com',
    storageBucket: 'bookstash-14e34.firebasestorage.app',
    measurementId: 'G-EKY4TWTRQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNakA6R6KyS4cmdf57AmMGvkpjqv0RSw',
    appId: '1:531941429147:android:08d19efd8138a51c611b3e',
    messagingSenderId: '531941429147',
    projectId: 'bookstash-14e34',
    storageBucket: 'bookstash-14e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAY-RVnuIQKsoBerIlp5iMRkkH3pJDtI',
    appId: '1:531941429147:ios:7d84955d4a058a1e611b3e',
    messagingSenderId: '531941429147',
    projectId: 'bookstash-14e34',
    storageBucket: 'bookstash-14e34.firebasestorage.app',
    iosBundleId: 'com.example.bookstash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfAY-RVnuIQKsoBerIlp5iMRkkH3pJDtI',
    appId: '1:531941429147:ios:7d84955d4a058a1e611b3e',
    messagingSenderId: '531941429147',
    projectId: 'bookstash-14e34',
    storageBucket: 'bookstash-14e34.firebasestorage.app',
    iosBundleId: 'com.example.bookstash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4FKbB335o1rEe_kQHTLH_R04fvIUt5Do',
    appId: '1:531941429147:web:f45839e7ae74d93f611b3e',
    messagingSenderId: '531941429147',
    projectId: 'bookstash-14e34',
    authDomain: 'bookstash-14e34.firebaseapp.com',
    storageBucket: 'bookstash-14e34.firebasestorage.app',
    measurementId: 'G-YHE0C6TEW2',
  );
}
